package jext.sql;

import java.sql.SQLException;

public interface Connection extends java.sql.Connection {
    // DON'T delete
    // It is necessary to support 'stmt.setXXX(<name>, <value>)

    Statement createStatement() throws SQLException;
    Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;
    Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    PreparedStatement prepareStatement(String sqlx) throws SQLException;
    PreparedStatement prepareStatement(String sqlx, int resultSetType, int resultSetConcurrency) throws SQLException;
    PreparedStatement prepareStatement(String sqlx, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
    PreparedStatement prepareStatement(String sqlx, int autoGeneratedKeys) throws SQLException;
    PreparedStatement prepareStatement(String sqlx, int columnIndexes[]) throws SQLException;
    PreparedStatement prepareStatement(String sqlx, String columnNames[]) throws SQLException;

    CallableStatement prepareCall(String sql) throws SQLException;
    CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
    CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    void registerNamedQuery(String name, String statement) throws SQLException;
}
