package jext.sql;

import java.sql.SQLException;

public interface Connection extends java.sql.Connection {

    jext.sql.Statement createStatement() throws SQLException;

    jext.sql.PreparedStatement prepareStatement(String sqlx) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int resultSetType, int resultSetConcurrency) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int autoGeneratedKeys) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int columnIndexes[]) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, String columnNames[]) throws SQLException;
}
