package jext.sql;

import java.sql.CallableStatement;
import java.sql.SQLException;

public interface Connection extends java.sql.Connection {

    jext.sql.Statement createStatement() throws SQLException;
    jext.sql.Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;
    jext.sql.Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    jext.sql.PreparedStatement prepareStatement(String sqlx) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int resultSetType, int resultSetConcurrency) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int autoGeneratedKeys) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, int columnIndexes[]) throws SQLException;
    jext.sql.PreparedStatement prepareStatement(String sqlx, String columnNames[]) throws SQLException;


    jext.sql.CallableStatement prepareCall(String sql) throws SQLException;
    jext.sql.CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
    jext.sql.CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    // String nativeSQL(String sql) throws SQLException;
}
