package jext.swing;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Insets;

public class JMapFrame extends JFrame {
    private JPanel contentPane;

    public JMapFrame() {
        setTitle("Map");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        contentPane.setLayout(new BorderLayout());
        setContentPane(contentPane);

        // JMapPanel mapApplet = new JMapPanel();
        // mapPanel.add(mapApplet, BorderLayout.CENTER);
        createUIComponents();

        setSize(1440, 900);
        setLocationRelativeTo(null);
    }

    public JMapPanel getMapPanel() {
        Component c = contentPane.getComponent(0);
        return (JMapPanel) c;
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
        JMapPanel mapApplet = new JMapPanel();
        contentPane.add(mapApplet, BorderLayout.CENTER);
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public javax.swing.JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
